---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-inventory-writer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-inventory.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [create,update,patch]
