{{- if $.Values.inventoryWriters }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-inventory-writer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-inventory.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-inventory-writer
subjects:
{{- range $name, $subject := $.Values.inventoryWriters }}
- name: {{ $name }}
  {{- tpl (omit $subject "name" | toYaml) $ | nindent 2}}
{{- end }}
{{- end }}
