{{- range $namespace, $instance := .Values.operatorInstances }}
{{- $options := (dict) }}
{{- $_ := deepCopy (default (dict) $.Values.operatorInstanceDefaults) | mergeOverwrite $options }}
{{- $_ := deepCopy $instance | mergeOverwrite $options }}
{{- if $options.installPlanApprover.enabled }}
{{- $createSa := true }}
{{- if and (hasKey $options.installPlanApprover.serviceAccount "create") (not $options.installPlanApprover.serviceAccount.create) -}}
{{- $createSa = false }}
{{- end }}
{{- if $createSa }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if $options.installPlanApprover.serviceAccount }}
  {{- with $options.installPlanApprover.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  name: {{ $options.installPlanApprover.serviceAccount.name }}
  namespace: {{ $namespace }}
{{- end }}
---
{{- end }}
{{- end }}
