{{- if .Values.clusterRoleBindingss }}
{{- fail ".clusterRoleBindings is deprecated. Use .rbac.<name>.clusterRoleBinding" }}
{{- end }}
{{- range $name, $value := .Values.rbac }}
{{- with $value.clusterRoleBinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ default $name .name | trunc 63 | trimSuffix "-" }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- $_ := unset . "annotations" }}
{{- $_ := unset . "labels" }}
{{- $_ := unset . "name" }}
{{ toYaml . }}
{{- end }}
{{- end }}
