{{- range $namespace, $nsConfig := .Values.namespaces }}
{{- $nsName := tpl $namespace $ }}
{{- $rbac := (dict) }}
{{- $_ := deepCopy (default (dict) $.Values.namespaceDefaults.rbac) | mergeOverwrite $rbac }}
{{- $_ := deepCopy (default (dict) $nsConfig.rbac) | mergeOverwrite $rbac }}
{{- range $name, $rbacConfig := $rbac }}
{{- if $rbacConfig.role }}
{{- $role := $rbacConfig.role }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- with $role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $role.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ default $name $role.name }}
  namespace: {{ $nsName }}
{{- $_ := unset $role "annotations" }}
{{- $_ := unset $role "labels" }}
{{- $_ := unset $role "name" }}
{{ toYaml $role }}
---
{{- end }}
{{- end }}
{{- end }}
