{{- range $namespace, $nsConfig := .Values.namespaces }}
{{- $nsName := tpl $namespace $ }}
{{- $rbac := (dict) }}
{{- $_ := deepCopy (default (dict) $.Values.namespaceDefaults.rbac) | mergeOverwrite $rbac }}
{{- $_ := deepCopy (default (dict) $nsConfig.rbac) | mergeOverwrite $rbac }}
{{- range $name, $rbacConfig := $rbac }}
{{- if $rbacConfig.roleBinding }}
{{- $roleBinding := $rbacConfig.roleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- with $roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $roleBinding.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ default $name $roleBinding.name }}
  namespace: {{ $nsName }}
{{- $_ := unset $roleBinding "annotations" }}
{{- $_ := unset $roleBinding "labels" }}
{{- $_ := unset $roleBinding "name" }}
{{ toYaml $roleBinding }}
---
{{- end }}
{{- end }}
{{- end }}
