{{- range $namespace, $nsConfig := .Values.namespaces }}
{{- $nsName := tpl $namespace $ }}
{{- $imageRegistrySecrets := (dict) }}
{{- $_ := deepCopy (default (dict) $.Values.namespaceDefaults.imageRegistrySecrets) | mergeOverwrite $imageRegistrySecrets }}
{{- $_ := deepCopy (default (dict) $nsConfig.imageRegistrySecrets) | mergeOverwrite $imageRegistrySecrets }}
{{- range $name, $config := $imageRegistrySecrets }}
apiVersion: v1
kind: Secret
metadata:
  {{- with $config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ default $name $config.name }}
  namespace: {{ $nsName }}
data:
  .dockerconfigjson: {{ include "openshift-project.dockerconfigjson" $config.dockerConfig | b64enc }}
type: kubernetes.io/dockerconfigjson
---
{{- end }}
{{- end }}
