{{- range $namespace, $nsConfig := .Values.namespaces }}
{{- $nsName := tpl $namespace $ }}
{{- $rbac := (dict) }}
{{- $_ := deepCopy (default (dict) $.Values.namespaceDefaults.rbac) | mergeOverwrite $rbac }}
{{- $_ := deepCopy (default (dict) $nsConfig.rbac) | mergeOverwrite $rbac }}
{{- range $name, $rbacConfig := $rbac }}
{{- if hasKey $rbacConfig "serviceAccount" }}
{{- $serviceAccount := $rbacConfig.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ default $name $serviceAccount.name }}
  namespace: {{ $nsName }}
{{- $_ := unset $serviceAccount "annotations" }}
{{- $_ := unset $serviceAccount "labels" }}
{{- $_ := unset $serviceAccount "name" }}
{{- with $serviceAccount }}
{{ toYaml . | indent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
